apiVersion: apps/v1
kind: Deployment
metadata:
  name: lazysplit
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lazysplit
  template:
    metadata:
      labels:
        app: lazysplit
    spec:
      containers:
        - name: lazysplit
          image: lazysplit:local
          command: ["poetry", "run", "python", "src/main.py"]
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: lazysplit-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: lazysplit
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30000
