name: coverage-comment
on:
  push:
    branches: [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build coverage file
        run: |
          poetry run coverage run -m pytest -s && poetry run coverage xml

      - name: Display coverage
        uses: ewjoachim/coverage-comment-action@v1
        with:
          GITHUB_TOKEN: ${{ github.token }}
          COVERAGE_FILE: "coverage.xml"
          BADGE_ENABLED: "true"
          BADGE_FILENAME: coverage-comment-badge.json
          MINIMUM_GREEN: 80
          MINIMUM_ORANGE: 60
          COMMENT_TEMPLATE: ""
          DIFF_COVER_ARGS: ""