name: coverage-comment
on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  coverage-comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      - name: Build coverage file
        run: |
          poetry run coverage run -m pytest -s && poetry run coverage xml

      - name: Produce the coverage badge
        uses: insightsengineering/coverage-action@v2
        with:
          path: ./coverage.xml
          fail: false
          publish: true
          coverage-summary-title: "Code Coverage Summary"

      - name: Produce the coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: ./coverage.xml
          badge: false
          fail_below_min: false
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'

      - name: Cat coverage report
        run: |
          cat code-coverage-results.md